config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  validates :name, presence: true, uniqueness: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(book_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.delete
    redirect_to lists_path
  end

  def book_params
    params.require(:bookmark).permit(:movie_id, :list_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_lists)
    @list.save
    redirect_to lists_path
  end

  private

  def params_lists
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
          <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="https://static.vecteezy.com/system/resources/previews/006/294/291/non_2x/film-logo-initial-letter-v-movie-logo-design-template-element-eps10-vector.jpg" />
      </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="#">Messages</a>
                </li>
                <li class="nav-item dropdown">
                  <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" />
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="#">Action</a>
                    <a class="dropdown-item" href="#">Another action</a>
                    <a class="dropdown-item" data-turbo-method="delete" href="#">Log out</a>
                  </div>
                </li>
                <!--li class="nav-item"-->
                <!--/li-->
            </ul>
          </div>
        </div>
      </div>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://conwayyao.com/wp-content/uploads/2015/07/posters-compilation.jpg)">
  List
</div>


<div class="card-container">
  <% @lists.each do |list| %>
    <div class="card-product">
        <% if list.photo.attached? %>
          <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fill %>
        <% else %>
          <p>No photo</p>
        <% end %>
        <div class="card-product-infos">
          <%= link_to list.name, list_path(list) %>
        </div>
    </div>
  <% end %>
</div>
  <div class="text-center mt-4 mb-4" >
  <%= link_to "Add a New list", new_list_path, class: "btn btn-warning" %>
  </div>

  <div class="footer">
  <div class="footer-links">
  </div>
  <div class="footer-copyright">
    Movies.com 
  </div>
</div>

app/views/lists/new.html.erb
<%= simple_form_for [@list] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Submit", class: "btn btn-warning"%>
  <%= link_to "Cancel", lists_path, class: "btn btn-warning" %>
<% end %>

app/views/lists/show.html.erb
<div class="d-flex justify-content-between m-5">
<%= link_to "Back to Lists", lists_path, class: "btn btn-warning" %>
</div>


<div class="card-container ">
    <h1><%= @list.name %></h1>
    <% @list.bookmarks.each do |bookmark| %>
    <%= bookmark.movie.title %>

    <%= link_to "Delete", bookmark_path(bookmark), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "btn btn-warning" %>
    <% end %>
      <%= simple_form_for [@list, @bookmark] do |f| %>
        <%= f.input :comment %>
        <%= f.association :movie, as: :radio_buttons %>
        <%= f.submit "Submit", class: "btn btn-warning"%>
      <% end %>
    <% if @list.photo.attached? %>
      <%= cl_image_tag @list.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <p>No photo</p>
    <% end %>
</div>
<div class="footer">
  <div class="footer-links">
  </div>
  <div class="footer-copyright">
    Movies.com 
  </div>
</div>